env:
  global:
    - secure: r8HE496NzYmzybBwb7yhltbzbjcLhQADzx6N+96VnnD7f0p5U6z3JFu9uhtB5slkosJh4E2e6SW20Sfk9+I31SYWlNGWOIyk5149PMHkti4Rp9guPjUwm3wRV8/wTecptFmEvdY8gm7dFgc7C1+vz5FAzcHJNvi55zKpTS9bAprIeWsSqFtgsCCByYrn3h2bUVee7OqQ4RwanD+j1tFb0OyiOzCkRAu0RCbbrnbuJoa57nc2sgdqtFRtU5hz4p4BZhW/IMLicKG7The44C/xzVjTkG3RmEBZHx0z+k1A2DPlvrKztunDyn5gi8/b3Ow62P1gB74eYLDjsA+B2UBu9SFSkavpb0ZCI2GHuwGNUcCF1aBXEdGzFWwy6Wabh03/xzFSxpSsFwmkF8DzVpMFj6TrbTC939JX+ult0p+Z66bDMXf8hSKDWVTyL0C99pfY+xZOMxRl0uuYdsWA01+7z8j1rrPSbN/6SYoKi0Xu5GWbY6axb2CrUvc3tGso5Yn336KK4+0Nvk7uJXcgrHw28FjVnES6dzMT67k4WcXpoUxzlFewm9DV1HYhNx/PcO6XuPyTnrAEWiWHkNnGen/VU6tMP3EIKeo92X7GrlLH+ugUvn7buJS+kjgGrstf/KMGsypoPjtSAFAhxc5SD+2kqHydNEha6zIP+q/rqkwRgGI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-pihole-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
