env:
  global:
    - secure: LHrmCqsPFgfHaujiOCLJrhMwz/igpGXDc+VnOjAI22ZzZUSZ63/ESTqvR5eBK9toqR4iOvalcCWVKVUJgPJQuZ26cu95+pyt8ffBnxjnVk9TPg7209llLddfdygE69//5jEPrH9FXKvtIQE3IPPFL0uGKOZdSZZCrkocLvehqkyTUi8i7RaEdX1usiAdNm1sHDC2tmgAf+c4VmuQgJzsmXuEsJ4E7pZjqIf2rwIzPafy63P4LXOlHd+X1CWW+7GXZoRKMEZxEdzrKxb9DUEnpN60DxyFN32pX6Sn6fDsrDcuaAPwF8y5oB0AzsTnw9UJwXjN5m4i7XOvWySWhlV50QsaPCVjfY8jEeC7lR+BkwvagnzOWBEmG8LXCzxEqOcNrX7k1A5m6jqpNGdY8hxoSUMXw9PY/qWQrXt/9KZTNOwEm9cuKUWvAyJUN5N3rNcCMuy7E1yNZsRH1J31F6H7SzuhW+JQeL0FA7Pxgngo2A/3RmQOxK9h7881mJP1TO/dF/tvWILERi+8wiv7ZEe3SBPAbMDEDxbsKbV9fSyzQGLKZYL6wjZ17FN1+UAcPETE5eeyk3LMpIYM6n7oDSqyFtb4NH8lL0X6Wx5CglQgwRd5g+nuud9s+ApBRAWiTqiXVKM7Y6T95AJ/y80D6bfGnXYCynOO3nXO0kZi8ULMIcw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-pihole-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
