env:
  global:
    - secure: ilWgo/S8Ydx/n1s5MJIm3GzGQDPwS3HqLfY+0KrF5NlnqkdEI0IB7wPcG2izgxP0YCYit9wvbAJAjr/Td8Ory0disQULFc5y76KfKMOpjTFmjKg9iCYF4uh3rvXl4vhg+7YTAtPhG4JFIyMDTtIOnb2iH8CUdDvWoTsBFHaI6qG1LB3G9QuS3C147DGZYQfMztV9PcbabGOa3GncxspVEeOV8PM0p6fRNyauFif7SvaQvYDXnm/ucKjtc+yyB4D0Gs9Ma++KkOb0MMP/xbPILYy095BeND+lVD8HmiSeMq//G1lw55bXvyBYayih3RkFi8+JW/K9/ZWJ1ao3gt139xYACchTZ1Ouff1/qSzhjZCQ7YGMaJ/H0hiPK+DIfS/yI4oQx0xFR7u8U5YB4lDPL3ep8ierZMJWBBcTzNzcdGOHvGZ86RaxO0UA8fquJgaqmZh0Q6BMFHb65HUTCLqRWXfoK1DRB0/1t3tqan2WB7gfY0AkCplPOzxVcM5eRn+dzaEWunXS80GoyGfWB5w7644VO+xj/yaYfWV5L3zhyOK7Uog+8/ruRBpEIgf+6iXgYzTvuCgx7kjbLajSe0d4EkKaCw6EvzvFUEThYcNGVFQAQLZc7cga5dwb2qp7KQJ/UXQfKz5+fTFiT2rc6L5a29oPxbUEDKqKq30RgAa7iF4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-pihole-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
