env:
  global:
    - secure: I9gVjGD7eg4+LyIeWPpal5pjhp52myz815k0vEQaNwWYoUqSn0NfbJ7QiNCPIRVR9Ezj+ezQMIFtISRjUrZnc7I94weh8a1F1rIhyroHyk2/soEK+XJENmBT4FVFqJtYwIOOEGAJhnQCK1uVDUM4ddJn9L0d/qyYuqdqNrhH5Ts7Wysn/q9NOqtfxGhe4T/b6d5umUjLwhjBzSgc/0kor+pSGZ+8VBOXJs/8BOWN1+xzk2EAqDWhG7bgWtlW8/Cq5Se1mbEC/NGJYeTmIgFSESgKIaMyTjiDjRoWGhNaT+fiow63wLJmCkjWpQ8UF8txYXjOeNtXCPTpuz2WIQna6aFMqLuEV+DlzrzBfy2CHSIvdsqId2ce1H9WOVWMe3us2IIbYrgq7OmOgDQYjCzHOMcIPRCtUn5huZ1OvCDrmsX8ijoGFu6NDNSfNGHD1DjOBE5BtrxN9xXJLrqx5wS8XMx2UAoiggRKBwVHx/xjciwlStSoSZV9lmCXskEAdlS0gJNQMuEbH4RhmpFJNkxg6nzBE8eMcoECfxTtgjIEF+FeQ/AN1iRsjS0n5/oeUHxYq7opqh+LLqdtuivwcltbHgs4mwQz4ZJ3PnZF0eXeiu22HtE6LuqWjhw5VCWg+xU/AwASq4n/m44LNvn3VzO+NCfcEHYtfIaBtCeujeL91lU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-pihole-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
