env:
  global:
    - secure: MeL0yoXRr1xcbrTd1ii4OkK0KT6PC+wxJihfVXqI2m/hVol9WHQPWKtldKhpJmMMg0zI7ac1rsujlU2VHxRO/Ydnaictk6/1M4Dd2AIGHW8MHgPlX40gBnc1Mad7lfDrQNBTKRTPCgP4Wrv9GLWJWyZrpLhi2g1Se3dPNjgwKfvY7xI99ujDzwbWFFW9GpyYsU7RPnuRoH/C/E077e9yws/C/Zry/o6P7qjM+5+k+k/GRYzDEoZ+VFoz1NdvXMc/2D7niCHanTOZAhapVSIedOTg+kUxjvoAR1RskxI26U2/TSEx5Z5PHWs6S2J4Ino20m2cSL3UZ0LEQZmHVZ4nrp9Lzy9XpFiooJHF3T7fn6rqabl2kwOYfTl8xCkg0Bzcepz4EKPZzZrOpCs9jv2KkZ8kt++UNdPsk17vDoBc0Lf0Gkp1BP6delQyl0Wrqgc21tFuTl+ytcnkprv8gfG5Ka+hF9GTudQs4SFKDfFk3KVAaDJ9VdMRy9RARiI+R/FHy8x9mSAWiVd+gCcobe6cJCa89H2bQpAgJpyYS5EVUSztfK2LVA84yooJnjCYIHHwMifzriAmYh/xDYZo2DG6OBo/Fvc8P8rmMhab2JyJTU7Z9WNU94w/GzK3/XmE7GuIyoZuIXJm4aJYIhdJuLRY0h2UxJNZdDPyEOzCRoko+EM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: funilrys@outlook.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-pihole-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - sudo apt-get -y install dos2unix
  - pip3 install colorama

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
