env:
  global:
    - secure: eVNMnmmKnOt77c0PYj42DJy1yDGiR+7CTxAgkjcfC1/5mUkc8pInXQlW2aaXLTNctxJ8n/Kvj2trSrS9LzaUrrkw3BkSKULNLd9P5jY4h6FkZUYZ32OAeBD9JArSX2SVToAxW1KP+7zoJoKDMcitIMVmZ3gFur3KVJ0ZVxpVYsHvxYTf7VRt8dUVPI5vARP8MthjRArudNlegbiSpvpKCRKBUWWb+594fxl6VglQUl+jsJvOTsS4HpcKtkXyZk17OlR4x/SwG7ASoDqDZU9IkIMxfyTxKI+rydt1vBNYlAyoBnQTPhf0TUNUMU2cbAVlYaJXgzIPn8wPdnTDh7B8X+Ba8D+R94VtLZod0JDC8AovILy1bPEwwpdf33FpX/aA/KXVNhAf+D/GwK28JZ8BJfS9u2j8wCAd1VPvTQWaU4zIpG5R/m8pqBNvSay3BjC+H5m7HV3Wo3E18AAic2B4lIklcwV1ae2uo+CeQBqKZQpNxlhg0bybBy5lCf6/+gqPi1WKZ42HclNT+wynNCA6iJlYbP0plTkrWQl8CN8xJsUGe7i3MUvjwfqWuxp6CZGTtUSFcnrgFCi5q1cyvKUO8uQtMFmRi5kyMHDmRvEzk/XckIazRXz1AT09Bnnk4eYNs0jNXPjlnYsXE6JYI83dS9KzeTnfak/ydJ47Xe570S0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-pihole-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
