env:
  global:
    - secure: EJCF+12OZb8m7KX0nMiifzdssAgG+nv38dNMTkhUCW43TUfVenhj1FHX44JWU4pE2E8IWRrUIInSxwHoeBV7fL/PraNg823X4sK2AMfvZgSs9bMil8KMkFV9bIDVKNuSlgEVAkcjy/ZrvjN9SEz4UAmTR+rvRSGcUt52lwRaf1Ubh1OHuvIb6b6B7iM5nXBl1+xiH3WcpRWWGBkNR85M3z7yuCI+1OtSzOR/R6oI9ZBH/WlTrslrTbhTJbArTbamDIP9DYVUMwFjyEsMycM7MbYVBjd0mr11JtvpO5W0TeG/r3/ub8ldDd5keubyvoUqOO+cO1C4BjEc9/ZFzIS1gCMmc2LCam5l+RgC6FeZmx9b6yw8GIb0oGTbDTI52RRNDbXGA7P6yfKJ6kuVRBxk0rHPduGxlhpQoKEXSQTC5qsqr6vWFQj8jjwCMXtBMtINnmoJ9TBQd4ImNASoNLv9LYkRdSoVELgiAOxi4I6jymmYKUV2KL2Sfk8EWQGyrGzq5oANmrmB88keAta1Bh3KemuQs8FCpH2bx2cyalFOpKZIsZD0XfD2q1Q+iuMcoXnOGFkv/bDiBFmllBSgxQpF2RSTs241n+Y5KpMULjBsnHxuMKNM59vdy3WqWMNPxnTPMDUv3L917K2YfmH3WS6dylqpmcUyd85jv3f8CofLTsU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-pihole-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
