env:
  global:
    - secure: nznM8iQHQlpE0NxIK661F0vanHPgV9g8FrlhguQuVfnV5R7WESdlyEA6LTJbb/EF76TJsgF7bOGvWJf/7Ei3+cDpgx5ytPpqa8tsvo326vyHdqEuGNMNOEq1EA62WXKXaCrWaY+TYY5a4o4IMILaDnlVcpSAiaD38NlCSlhB1VDwSxSSN8x0vTBy3YA4oD4sZ7fZEF4WHjLrq6D2YCClcWpFbwdQ5O0jgp1mcraec6nOmWiIc4UywhwgvyYHYI8G4VLfw/pV9m9F0ZDeKurjK5fNx8XhulBLW4tesRRt2EGzSqe9d7JQuf1GN71IyFdnlZuY6DTe9Tmwz6vtC+VF3tzZ32Cy71i/ABDF3/zlpqwlHPw/aHU07t/KkdRo6KxmyArX5DD61yZUdAGKjwQtKAV5sEHFxppA74ClK2gdQj6zjOT/evhT3d73Dh6DQy0AnTv4UG2P3aYQvd6MfHjehtNP4yaEJct66xPZgsszkRZZQw0T05N9ch/o+N5VH67JgK5YNjYsNNMccMSqH2SDk7YwgN4JcLzL+tptXxzF3CJeqpaiOLC0RP+OF72TCv0cyq7Ea2mN+VjoYcrSZZ1/nX7nMq51inla1QA3BmwUwAiLop8QTAqecVQ5XeJsCfGfoKxftC+ECRIKqSqEXpTVWDRnYRagc1YKivPHTlX56iY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-pihole-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
