env:
  global:
    - secure: Lycc4HzPQE9HG4ZuAxej1ZEDbM+1nPRcW823+e8SK0xH/g4trdAQqSQG6hxS+YcSn6hCSkTj/VX/Z8AFg3dxs7mmjGCoDteoGmuz4PMfvtfFkdwiO0hXvITzdUY5WmzILTUU2lyGUB3R9Wz6v0RcEMUsr28mg2xhb2ddIg5wxDiFaSMd8Y1YAUmdkGD9WqHl77moZk8WoNpxtw23C3SBpkPopb/D+k57EbSWVdPz/GtDo58vxcWiORGA8lphPddRQmQJGHJ/yH8j7uV9/ipSuZXTAKcv8Q5l1u0ycIAONKIUSokkqWqBLADVSfOEaTyKDQ/fNra6Dkna6rr4UPdA0sgmv8NuO557maxWZ79T+x1+FmOmccmYJuHdSLc2hHXYUtUE11iyWkE/2QMlvqRS6gKgTSkjhv8RMmaLyTCizNJsREZ58Is6/VmFfixBC2fzmHFkbqjJquS3SvAzlpVWeML+RpTE2MDbEVu34/3iANDfd5MnQu5uvvLxbozPlsol7S/DIUa/BDIUNd/vJTF1xQBnAFek2xuLaPrlTdWF9zTNtB9xnm0fvOM1CUWEAJQogm+NEy0Sg6ru1nW/OrpSxZKQQtcPakzEdAP8gxSBDOY48r3dydoZ7s7kAJi/3xzC+rMB4YdwF4zr6K+PvlpxwDTMgdpxi2CNtQzoooA2a7Y=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-pihole-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
