env:
  global:
    - secure: pYh82KfA0VS9z3DhZbDWFkqKc1FjCfeOwCG9nUbMr0P2k6exOqr9uU29757El4EuDQzcLh7ufZLkh4EY+LSCjgE1s7Trt8KFOXXQY+IjKLVlUZBufNyb2Oa5pnOgLwHo+hHIEq0XTsoxl6uGEmUQX75W5kM/137ZGNhGL6e4zrrqErMaVZ57JM9z02nhEAGHtJel7N62CmX6ZdWK261h2r65Uag4rwuVlS+jpEIwdH+IoHtxCidwZJWis4AsJUgrg7td8sXpEEx17yC05b5UlpdBZSgu7vPelGXL86flNiu+ohAJjQwbkPNYiL8O22smqO6gbKi064qvopoZAyyfws/l0GRXdIyxu2rWshEMZE9G6cI9ay6dcVlcYMtLuN4GZNnZyvzjxw7cRGSqE4aRihLDwvcmSJljw6T+tQpULXUaSJsEl9F36je1RuUf8/A7B094aBMZYTQmzsWCyCmKB1zcJcYfLtZ/PW9AD+e4PtbWRHRAZv9wK2jyvUJupatPcpj5QKKr8s++KWg8CvVkaCeuJ4fSQwTcoV7Ddx+yFVDagw0ehQCAff8DhX6bT80FHkRbJ4h9GhUT7vM/ODIr5I/tjeQ1JsueD28khmBXZf8ACFBGiGD/p3KarEEJ5bC2gssAnDWmMRDBxe7Xbupa/eLOfEM6wJ+1cFX3++D751o=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-pihole-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
